version: '3'
services:
    web:
        build: 
            context: .
            dockerfile: neuralm-web.DockerFile
        depends_on: 
            - "messagequeue"
        ports:
            - "3333:80"
        networks:
            - neuralm-network
        image: glovali/web:latest
    messagequeue:
        build: 
            context: .
            dockerfile: neuralm-messagequeue.DockerFile
        ports:
            - "5000:5000"
            - "5001:5001"
        networks:
            - neuralm-network
        image: glovali/messagequeue:latest
    registryservice:
        build: 
            context: .
            dockerfile: neuralm-registryservice.DockerFile
        depends_on: 
            - "messagequeue"
            - "registrydb"
        ports:
            - "5002:80"
        environment:
            WAIT_HOSTS: messagequeue:5001, registrydb:1433
        networks:
            - neuralm-network
        image: glovali/registryservice:latest
    userservice:
        build: 
            context: .
            dockerfile: neuralm-userservice.DockerFile
        depends_on: 
            - "registryservice"
            - "userdb"
        ports:
            - "5003:80"
        environment:
            WAIT_HOSTS: userdb:1433
        networks:
            - neuralm-network
        image: glovali/userservice:latest
    trainingroomservice:
        build: 
            context: .
            dockerfile: neuralm-trainingroomservice.DockerFile
        depends_on: 
            - "registryservice"
            - "trainingroomdb"
        ports:
            - "5004:80"
        environment:
            WAIT_HOSTS: trainingroomdb:1433
        networks:
            - neuralm-network
        image: glovali/trainingroomservice:latest
    userdb:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        networks:
            - neuralm-network
    registrydb:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        networks:
            - neuralm-network
    trainingroomdb:
        image: "mcr.microsoft.com/mssql/server"
        environment:
            SA_PASSWORD: "Your_password123"
            ACCEPT_EULA: "Y"
        networks:
            - neuralm-network
networks:
    neuralm-network:
        driver: bridge