name: .NET Core

on:
  push:
    branches: 
      - master
      - development

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
      - name: Building the docker image
      - run: DOCKER_Build_Command # Docker command to run the docker
    
  deployregistry:
    if: contains(github.ref, 'master')
    runs-on: ubuntu-latest
    needs: [build]
    steps:
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.8
      with:
        name: myDocker/repository #Your docker repository
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: MyDockerFileName #Your docker file
